## Exploratory Data Analysis - Before Preprocessing

This notebook performs exploratory data analysis (EDA) on the raw dataset 
before applying any preprocessing steps.

### Following issues:
1. **Check overview structure**: function overview_structure
2. **Get data (lattitude, longtitude, date)**: function get_lat_lon, get_date
3. **Check missing values**: function check_missing_values
4. **Check duplicate rows**: function check_duplicate_rows
5. **Describe data (min, max, quantile, std)**: function describe_data

In [3]:
import pandas as pd

In [4]:
df_CaMau = pd.read_csv('/kaggle/input/raw-at-data/DATA_SENT SV/Ca Mau_Final.csv')
df_LangSon = pd.read_csv('/kaggle/input/raw-at-data/DATA_SENT SV/Lang Son_Final.csv')
df_LaoCai = pd.read_csv('/kaggle/input/raw-at-data/DATA_SENT SV/Lao Cai_Final.csv')
df_NoiBai = pd.read_csv('/kaggle/input/raw-at-data/DATA_SENT SV/NoiBai_Final.csv')
df_PhuBai = pd.read_csv('/kaggle/input/raw-at-data/DATA_SENT SV/Phu Bai_Final.csv')
df_QuyNhon = pd.read_csv('/kaggle/input/raw-at-data/DATA_SENT SV/Quy Nhon_Final.csv')
df_TPHCM = pd.read_csv('/kaggle/input/raw-at-data/DATA_SENT SV/TPHCM_Final.csv')
df_Vinh = pd.read_csv('/kaggle/input/raw-at-data/DATA_SENT SV/Vinh_Final.csv')

station_dfs = {
    'Noi_Bai': df_NoiBai,
    'Lang_Son': df_LangSon,
    'Lao_Cai': df_LaoCai,

    'Vinh': df_Vinh,
    'Phu_Bai': df_PhuBai,
    'Quy_Nhon': df_QuyNhon,

    'TPHCM': df_TPHCM,
    'Ca_Mau': df_CaMau
}

In [14]:
def overview_structure(station_dfs):
    for station_name, station_df in station_dfs.items():
        print(f"------STATION {station_name.upper()}------")
        print(station_df.info())
        print("\n")

overview_structure(station_dfs)

------STATION NOI_BAI------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12653 entries, 0 to 12652
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   YMD        12653 non-null  object
 1   NAME       12653 non-null  object
 2   LATITUDE   12653 non-null  float64
 3   LONGITUDE  12653 non-null  float64
 4   YEAR       12653 non-null  int64
 5   MONTH      12653 non-null  int64
 6   DAY        12653 non-null  int64
 7   TMP_2      12653 non-null  float64
 8   DEW_2      12653 non-null  float64
 9   RH         12653 non-null  float64
 10  AT mean    12653 non-null  float64
 11  AT max     12653 non-null  float64
dtypes: float64(7), int64(3), object(2)
memory usage: 1.2+ MB
None


------STATION LANG_SON------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11880 entries, 0 to 11879
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   YMD        11880 non-null  object
 1   NAME       11880 non-null  object
 2   LATITUDE   11880 non-null  float64
 3   LONGITUDE  11880 non-null  float64
 4   YEAR       11880 non-null  int64
 5   MONTH      11880 non-null  int64
 6   DAY        11880 non-null  int64
 7   DEW_2      11880 non-null  float64
 8   TMP_2      11880 non-null  float64
 9   RH         11880 non-null  float64
 10  AT mean    11880 non-null  float64
 11  AT max     11880 non-null  float64
dtypes: float64(7), int64(3), object(2)
memory usage: 1.1+ MB
None


------STATION LAO_CAI------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11775 entries, 0 to 11774
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   YMD        11775 non-null  object
 1   NAME       11775 non-null  object
 2   LATITUDE   11775 non-null  float64
 3   LONGITUDE  11775 non-null  float64
 4   YEAR       11775 non-null  int64
 5   MONTH      11775 non-null  int64
 6   DAY        11775 non-null  int64
 7   DEW_2      11775 non-null  float64
 8   TMP_2      11775 non-null  float64
 9   RH         11775 non-null  float64
 10  AT mean    11775 non-null  float64
 11  AT max     11775 non-null  float64
dtypes: float64(7), int64(3), object(2)
memory usage: 1.1+ MB
None


------STATION VINH------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12638 entries, 0 to 12637
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   YMD        12638 non-null  object
 1   NAME       12638 non-null  object
 2   LATITUDE   12638 non-null  float64
 3   LONGITUDE  12638 non-null  float64
 4   YEAR       12638 non-null  int64
 5   MONTH      12638 non-null  int64
 6   DAY        12638 non-null  int64
 7   TMP_2      12637 non-null  float64
 8   DEW_2      12637 non-null  float64
 9   RH         12637 non-null  float64
 10  AT mean    12637 non-null  float64
 11  AT max     12637 non-null  float64
dtypes: float64(7), int64(3), object(2)
memory usage: 1.2+ MB
None


------STATION PHU_BAI------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11824 entries, 0 to 11823
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   YMD        11824 non-null  object
 1   NAME       11824 non-null  object
 2   LATITUDE   11824 non-null  float64
 3   LONGITUDE  11824 non-null  float64
 4   YEAR       11824 non-null  int64
 5   MONTH      11824 non-null  int64
 6   DAY        11824 non-null  int64
 7   TMP_2      11824 non-null  float64
 8   DEW_2      11824 non-null  float64
 9   RH         11824 non-null  float64
 10  AT mean    11824 non-null  float64
 11  AT max     11824 non-null  float64
dtypes: float64(7), int64(3), object(2)
memory usage: 1.1+ MB
None


------STATION QUY_NHON------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12634 entries, 0 to 12633
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   YMD        12634 non-null  object
 1   NAME       12634 non-null  object
 2   LATITUDE   12634 non-null  float64
 3   LONGITUDE  12634 non-null  float64
 4   YEAR       12634 non-null  int64
 5   MONTH      12634 non-null  int64
 6   DAY        12634 non-null  int64
 7   TMP_2      12634 non-null  float64
 8   DEW_2      12634 non-null  float64
 9   RH         12634 non-null  float64
 10  AT mean    12634 non-null  float64
 11  AT max     12634 non-null  float64
dtypes: float64(7), int64(3), object(2)
memory usage: 1.2+ MB
None


------STATION TPHCM------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12658 entries, 0 to 12657
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   YMD        12658 non-null  object
 1   NAME       12658 non-null  object
 2   LATITUDE   12658 non-null  float64
 3   LONGITUDE  12658 non-null  float64
 4   YEAR       12658 non-null  int64
 5   MONTH      12658 non-null  int64
 6   DAY        12658 non-null  int64
 7   TMP_2      12658 non-null  float64
 8   DEW_2      12658 non-null  float64
 9   RH         12658 non-null  float64
 10  AT mean    12658 non-null  float64
 11  AT max     12658 non-null  float64
dtypes: float64(7), int64(3), object(2)
memory usage: 1.2+ MB
None


------STATION CA_MAU------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12608 entries, 0 to 12607
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   YMD        12608 non-null  object
 1   NAME       12608 non-null  object
 2   LATITUDE   12608 non-null  float64
 3   LONGITUDE  12608 non-null  float64
 4   YEAR       12608 non-null  int64
 5   MONTH      12608 non-null  int64
 6   DAY        12608 non-null  int64
 7   DEW_2      12608 non-null  float64
 8   TMP_2      12608 non-null  float64
 9   RH         12608 non-null  float64
 10  AT mean    12608 non-null  float64
 11  AT max     12608 non-null  float64
dtypes: float64(7), int64(3), object(2)
memory usage: 1.2+ MB
None

In [6]:
def get_lat_lon(station_dfs):
    for station_name, station_df in station_dfs.items():
        print(f"------STATION {station_name.upper()}------")
        print(f"Longitude: {station_df['LONGITUDE'][0]}")
        print(f"Latitude: {station_df['LATITUDE'][0]}")

get_lat_lon(station_dfs)

------STATIONL NOI_BAI------
Longitude: 105.81
Latitude: 21.22
------STATIONL LANG_SON------
Longitude: 106.7666666
Latitude: 21.8333333
------STATIONL LAO_CAI------
Longitude: 103.9666666
Latitude: 22.5
------STATIONL VINH------
Longitude: 105.67
Latitude: 18.74
------STATIONL PHU_BAI------
Longitude: 107.7
Latitude: 16.4
------STATIONL QUY_NHON------
Longitude: 109.22
Latitude: 13.77
------STATIONL TPHCM------
Longitude: 106.65
Latitude: 10.82
------STATIONL CA_MAU------
Longitude: 105.15
Latitude: 9.1833333

In [7]:
def get_date(station_dfs):
    for station_name, station_df in station_dfs.items():
        ymd = pd.to_datetime(station_df[['YEAR', 'MONTH', 'DAY']])

        print(f"------STATION {station_name.upper()}------")
        print(f"First day: {ymd.min()}")
        print(f"Last day: {ymd.max()}")
        print(f"Years: {ymd.dt.year.max() - ymd.dt.year.min()}")
        print(f"Dates: {len(station_df)}")

get_date(station_dfs)

------STATION NOI_BAI------
First day: 1990-01-01 00:00:00
Last day: 2024-08-31 00:00:00
Years: 34
Dates: 12653
------STATION LANG_SON------
First day: 1990-01-04 00:00:00
Last day: 2024-08-31 00:00:00
Years: 34
Dates: 11880
------STATION LAO_CAI------
First day: 1992-04-01 00:00:00
Last day: 2024-08-31 00:00:00
Years: 32
Dates: 11775
------STATION VINH------
First day: 1990-01-01 00:00:00
Last day: 2024-08-31 00:00:00
Years: 34
Dates: 12638
------STATION PHU_BAI------
First day: 1992-04-01 00:00:00
Last day: 2024-08-31 00:00:00
Years: 32
Dates: 11824
------STATION QUY_NHON------
First day: 1990-01-01 00:00:00
Last day: 2024-08-31 00:00:00
Years: 34
Dates: 12634
------STATION TPHCM------
First day: 1990-01-01 00:00:00
Last day: 2024-08-31 00:00:00
Years: 34
Dates: 12658
------STATION CA_MAU------
First day: 1990-01-02 00:00:00
Last day: 2024-08-31 00:00:00
Years: 34
Dates: 12608

In [8]:
def check_missing_values(station_dfs):
    for station_name, station_df in station_dfs.items():
        print(f"------STATION {station_name.upper()}------")
        print(station_df.isnull().sum())

check_missing_values(station_dfs)

------STATION NOI_BAI------
YMD          0
NAME         0
LATITUDE     0
LONGITUDE    0
YEAR         0
MONTH        0
DAY          0
TMP_2        0
DEW_2        0
RH           0
AT mean      0
AT max       0
dtype: int64
------STATION LANG_SON------
YMD          0
NAME         0
LATITUDE     0
LONGITUDE    0
YEAR         0
MONTH        0
DAY          0
DEW_2        0
TMP_2        0
RH           0
AT mean      0
AT max       0
dtype: int64
------STATION LAO_CAI------
YMD          0
NAME         0
LATITUDE     0
LONGITUDE    0
YEAR         0
MONTH        0
DAY          0
DEW_2        0
TMP_2        0
RH           0
AT mean      0
AT max       0
dtype: int64
------STATION VINH------
YMD          0
NAME         0
LATITUDE     0
LONGITUDE    0
YEAR         0
MONTH        0
DAY          0
TMP_2        1
DEW_2        1
RH           1
AT mean      1
AT max       1
dtype: int64
------STATION PHU_BAI------
YMD          0
NAME         0
LATITUDE     0
LONGITUDE    0
YEAR         0
MONTH        0
DAY          0
TMP_2        0
DEW_2        0
RH           0
AT mean      0
AT max       0
dtype: int64
------STATION QUY_NHON------
YMD          0
NAME         0
LATITUDE     0
LONGITUDE    0
YEAR         0
MONTH        0
DAY          0
TMP_2        0
DEW_2        0
RH           0
AT mean      0
AT max       0
dtype: int64
------STATION TPHCM------
YMD          0
NAME         0
LATITUDE     0
LONGITUDE    0
YEAR         0
MONTH        0
DAY          0
TMP_2        0
DEW_2        0
RH           0
AT mean      0
AT max       0
dtype: int64
------STATION CA_MAU------
YMD          0
NAME         0
LATITUDE     0
LONGITUDE    0
YEAR         0
MONTH        0
DAY          0
DEW_2        0
TMP_2        0
RH           0
AT mean      0
AT max       0
dtype: int64

In [9]:
def check_duplicate_rows(station_dfs):
    for station_name, station_df in station_dfs.items():
        print(f"------STATION {station_name.upper()}------")
        print(station_df.duplicated().sum())

check_duplicate_rows(station_dfs)

------STATION NOI_BAI------
0
------STATION LANG_SON------
0
------STATION LAO_CAI------
0
------STATION VINH------
0
------STATION PHU_BAI------
0
------STATION QUY_NHON------
0
------STATION TPHCM------
0
------STATION CA_MAU------
0

In [10]:
def describe_data(station_dfs):
    for station_name, station_df in station_dfs.items():
        print(f"------STATION {station_name.upper()}------")
        print(station_df.describe())

describe_data(station_dfs)

------STATION NOI_BAI------
           LATITUDE     LONGITUDE          YEAR         MONTH           DAY  \
count  1.265300e+04  1.265300e+04  12653.000000  12653.000000  12653.000000
mean   2.122000e+01  1.058100e+02   2006.839959      6.482494     15.730973
std    3.872611e-13  3.315523e-11     10.008054      3.441294      8.798758
min    2.122000e+01  1.058100e+02   1990.000000      1.000000      1.000000
25%    2.122000e+01  1.058100e+02   1998.000000      4.000000      8.000000
50%    2.122000e+01  1.058100e+02   2007.000000      6.000000     16.000000
75%    2.122000e+01  1.058100e+02   2016.000000      9.000000     23.000000
max    2.122000e+01  1.058100e+02   2024.000000     12.000000     31.000000

              TMP_2         DEW_2            RH       AT mean        AT max
count  12653.000000  12653.000000  12653.000000  12653.000000  12653.000000
mean      24.367013     20.088642     78.579162     21.875167     25.217853
std        5.217426      5.688532     10.082696      5.266005      5.931446
min        6.916667      0.585714     31.166667      4.265262      5.360200
25%       20.587500     16.487500     73.000000     18.068165     21.195500
50%       25.600000     21.841667     79.833333     23.127711     26.463700
75%       28.541667     24.743478     85.565217     26.093159     29.855590
max       35.333333     28.679167    100.000000     32.796837     38.529400
------STATION LANG_SON------
           LATITUDE     LONGITUDE          YEAR         MONTH           DAY  \
count  1.188000e+04  1.188000e+04  11880.000000  11880.000000  11880.000000
mean   2.183333e+01  1.067667e+02   2007.827525      6.506397     15.731650
std    4.064476e-12  1.048805e-11      9.432083      3.434198      8.796712
min    2.183333e+01  1.067667e+02   1990.000000      1.000000      1.000000
25%    2.183333e+01  1.067667e+02   2000.000000      4.000000      8.000000
50%    2.183333e+01  1.067667e+02   2008.000000      7.000000     16.000000
75%    2.183333e+01  1.067667e+02   2016.000000      9.000000     23.000000
max    2.183333e+01  1.067667e+02   2024.000000     12.000000     31.000000

              DEW_2         TMP_2            RH       AT mean        AT max
count  11880.000000  11880.000000  11880.000000  11880.000000  11880.000000
mean      18.237528     21.836145     80.552764     19.331163     22.937271
std        6.263560      5.843147      9.832910      5.899003      6.577985
min        0.100000      2.300000     38.170261     -0.336200     -0.336200
25%       13.923750     17.750000     75.008730     15.194242     18.814070
50%       20.125000     23.400000     81.471369     20.922067     24.416030
75%       23.650000     26.550000     87.763015     24.096912     28.194810
max       27.275000     32.950000    118.971746     30.439725     37.414200
------STATION LAO_CAI------
       LATITUDE     LONGITUDE          YEAR         MONTH           DAY  \
count   11775.0  1.177500e+04  11775.000000  11775.000000  11775.000000
mean       22.5  1.039667e+02   2007.973843      6.519406     15.727473
std         0.0  1.276189e-11      9.344382      3.432096      8.799507
min        22.5  1.039667e+02   1992.000000      1.000000      1.000000
25%        22.5  1.039667e+02   2000.000000      4.000000      8.000000
50%        22.5  1.039667e+02   2008.000000      7.000000     16.000000
75%        22.5  1.039667e+02   2016.000000      9.000000     23.000000
max        22.5  1.039667e+02   2024.000000     12.000000     31.000000

              DEW_2         TMP_2            RH       AT mean        AT max
count  11775.000000  11775.000000  11775.000000  11775.000000  11775.000000
mean      20.417228     24.126165     80.201086     21.640792     25.123444
std        4.797033      5.110257      7.571291      5.149261      5.804909
min        3.600000      6.785714     34.206361      4.170249      4.757680
25%       16.950000     20.406250     75.414891     17.891292     21.018860
50%       21.714286     25.287500     80.207838     22.808461     26.105880
75%       24.600000     28.226786     85.345525     25.781272     29.730180
max       28.012500     35.000000    100.000000     32.545510     38.859630
------STATION VINH------
           LATITUDE     LONGITUDE          YEAR         MONTH           DAY  \
count  1.263800e+04  1.263800e+04  12638.000000  12638.000000  12638.000000
mean   1.874000e+01  1.056700e+02   2006.836683      6.482988     15.732078
std    2.892023e-12  1.648524e-12     10.010831      3.441341      8.802785
min    1.874000e+01  1.056700e+02   1990.000000      1.000000      1.000000
25%    1.874000e+01  1.056700e+02   1998.000000      4.000000      8.000000
50%    1.874000e+01  1.056700e+02   2007.000000      6.000000     16.000000
75%    1.874000e+01  1.056700e+02   2016.000000      9.000000     23.000000
max    1.874000e+01  1.056700e+02   2024.000000     12.000000     31.000000

              TMP_2         DEW_2            RH       AT mean        AT max
count  12637.000000  12637.000000  12637.000000  12637.000000  12637.000000
mean      24.752894     21.252620     82.398538     22.276542     25.230195
std        5.140137      4.211850     10.039780      5.166960      5.942381
min        7.287500      2.537500     44.714286      4.666893      5.913810
25%       20.900000     18.758333     77.000000     18.401966     20.921780
50%       25.487500     22.758333     84.833333     23.037109     25.726640
75%       28.800000     24.571429     89.875000     26.363961     29.840290
max       35.428571     27.612500    100.000000     32.891513     40.119800
------STATION PHU_BAI------
           LATITUDE     LONGITUDE          YEAR         MONTH           DAY  \
count  1.182400e+04  1.182400e+04  11824.000000  11824.000000  11824.000000
mean   1.640000e+01  1.077000e+02   2007.968539      6.514631     15.732070
std    3.503124e-12  2.400315e-11      9.364336      3.431763      8.802163
min    1.640000e+01  1.077000e+02   1992.000000      1.000000      1.000000
25%    1.640000e+01  1.077000e+02   2000.000000      4.000000      8.000000
50%    1.640000e+01  1.077000e+02   2008.000000      7.000000     16.000000
75%    1.640000e+01  1.077000e+02   2016.000000      9.000000     23.000000
max    1.640000e+01  1.077000e+02   2024.000000     12.000000     31.000000

              TMP_2         DEW_2            RH       AT mean        AT max
count  11824.000000  11824.000000  11824.000000  11824.000000  11824.000000
mean      25.598005     22.348304     83.964388     23.133346     27.123484
std        4.038053      2.744707      9.071877      4.050585      5.363780
min       12.170833     10.640000     47.958333      9.618527     10.454130
25%       22.812500     20.875000     78.250000     20.335426     23.512300
50%       26.231250     23.350000     85.443452     23.784043     27.734530
75%       28.775000     24.325000     90.750000     26.321280     31.527030
max       35.150000     28.416667    100.000000     32.650240     39.552470
------STATION QUY_NHON------
           LATITUDE     LONGITUDE          YEAR         MONTH           DAY  \
count  1.263400e+04  1.263400e+04  12634.000000  12634.000000  12634.000000
mean   1.377000e+01  1.092200e+02   2006.840431      6.481795     15.732310
std    1.581020e-12  2.242562e-11     10.009432      3.441201      8.802856
min    1.377000e+01  1.092200e+02   1990.000000      1.000000      1.000000
25%    1.377000e+01  1.092200e+02   1998.000000      4.000000      8.000000
50%    1.377000e+01  1.092200e+02   2007.000000      6.000000     16.000000
75%    1.377000e+01  1.092200e+02   2016.000000      9.000000     23.000000
max    1.377000e+01  1.092200e+02   2024.000000     12.000000     31.000000

              TMP_2         DEW_2            RH       AT mean        AT max
count  12634.000000  12634.000000  12634.000000  12634.000000  12634.000000
mean      27.351584     23.012210     78.206357     24.886562     27.789311
std        2.764106      2.334726      8.100896      2.773664      3.438005
min       17.733333     10.262500     48.250000     15.184563     15.656590
25%       25.262500     21.775000     74.375000     22.796669     25.170020
50%       27.550000     23.516667     79.375000     25.094477     28.050325
75%       29.525000     24.700000     83.500000     27.073149     30.332317
max       35.625000     27.942857     97.285714     33.125833     47.447860
------STATION TPHCM------
           LATITUDE     LONGITUDE         YEAR         MONTH           DAY  \
count  1.265800e+04  1.265800e+04  12658.00000  12658.000000  12658.000000
mean   1.082000e+01  1.066500e+02   2006.83465      6.483252     15.731711
std    3.513773e-12  8.029450e-12     10.00993      3.441206      8.798280
min    1.082000e+01  1.066500e+02   1990.00000      1.000000      1.000000
25%    1.082000e+01  1.066500e+02   1998.00000      4.000000      8.000000
50%    1.082000e+01  1.066500e+02   2007.00000      6.000000     16.000000
75%    1.082000e+01  1.066500e+02   2016.00000      9.000000     23.000000
max    1.082000e+01  1.066500e+02   2024.00000     12.000000     31.000000

              TMP_2         DEW_2            RH       AT mean        AT max
count  12658.000000  12658.000000  12658.000000  12658.000000  12658.000000
mean      27.913488     23.234131     77.588707     25.448489     30.116648
std        1.555561      2.078495      9.170636      1.556620      1.936814
min       19.142857     12.200000     48.294118     16.642969     18.037650
25%       26.900000     22.193333     71.208333     24.438480     28.922357
50%       27.904167     23.797917     78.288690     25.437589     30.477950
75%       28.945833     24.689327     84.541667     26.477095     31.511730
max       33.371429     27.866667    100.000000     30.873925     36.582660
------STATION CA_MAU------
           LATITUDE     LONGITUDE          YEAR         MONTH           DAY  \
count  1.260800e+04  1.260800e+04  12608.000000  12608.000000  12608.000000
mean   9.183333e+00  1.051500e+02   2006.833994      6.485882     15.734296
std    9.965757e-13  6.466195e-12      9.997991      3.441744      8.796258
min    9.183333e+00  1.051500e+02   1990.000000      1.000000      1.000000
25%    9.183333e+00  1.051500e+02   1998.000000      4.000000      8.000000
50%    9.183333e+00  1.051500e+02   2007.000000      6.000000     16.000000
75%    9.183333e+00  1.051500e+02   2015.000000      9.000000     23.000000
max    9.183333e+00  1.051500e+02   2024.000000     12.000000     31.000000

              DEW_2         TMP_2            RH       AT mean        AT max
count  12608.000000  12608.000000  12608.000000  12608.000000  12608.000000
mean      23.825991     27.690382     79.808748     25.235778     28.382858
std        1.472636      1.451229      6.770842      1.454375      1.911248
min       14.412500     20.642857     54.189303     18.138345     18.927660
25%       23.069196     26.713839     74.956437     24.261363     27.243650
50%       24.266667     27.725000     79.481476     25.268824     28.528200
75%       24.862500     28.685714     84.613219     26.230568     29.699580
max       27.075000     32.833333     98.804017     30.358693     36.796760